---
".gitlab-ci.yml":
  delete: true
appveyor.yml:
  delete: true
Gemfile:
  optional:
    ":development":
      - gem: 'puppet-resource_api'
.rubocop.yml:
  include_todos: true
  profiles:
    strict:
      configs:
        RSpec/SpecFilePathFormat:
          Exclude:
          - spec/unit/puppet_x/puppetlabs/**/*_spec.rb
Rakefile:
  changelog_user: puppetlabs
  changelog_max_issues: 500
spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
.gitpod.Dockerfile:
  unmanaged: false
.gitpod.yml:
  unmanaged: false
.github/workflows/auto_release.yml:
  unmanaged: false
.github/workflows/ci.yml:
  unmanaged: false
  acceptance_flags:
    - '--nightly'
    - '--platform-exclude centos-7'
    - '--platform-exclude oraclelinux-7'
    - '--platform-exclude scientific-7'
    - '--platform-exclude centos-8'
    - '--platform-exclude rocky-8'
.github/workflows/nightly.yml:
  unmanaged: false
  acceptance_flags:
    - '--nightly'
    - '--platform-exclude centos-7'
    - '--platform-exclude oraclelinux-7'
    - '--platform-exclude scientific-7'
    - '--platform-exclude centos-8'
    - '--platform-exclude rocky-8'
.github/workflows/release.yml:
  unmanaged: false
.travis.yml:
  delete: true
changelog_since_tag: 'v3.0.0'
