---
.gitlab-ci.yml:
  unmanaged: true

.travis.yml:
  bundle_args: --without system_tests
  docker_sets:
    - set: docker/centos-7
    - set: docker/ubuntu-14.04
  docker_defaults:
    bundler_args: ""
  secure: ""
  branches:
    - release

appveyor.yml:
  delete: true

Gemfile:
  optional:
    ':development':
      - gem: 'github_changelog_generator'
        git: 'https://github.com/skywinder/github-changelog-generator'
        ref: '20ee04ba1234e9e83eb2ffb5056e23d641c7a018'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')"
  required:
    ':system_tests':
      - gem: 'puppet-module-posix-system-r#{minor_version}'
        platforms: ruby
      - gem: 'puppet-module-win-system-r#{minor_version}'
        platforms:
          - mswin
          - mingw
          - x64_mingw

spec/spec_helper.rb:
  mock_with: ':rspec'
  coverage_report: true
