---
".gitlab-ci.yml":
  delete: true
appveyor.yml:
  delete: true
Gemfile:
  optional:
    ":development":
      - gem: 'puppet-resource_api'
      - gem: github_changelog_generator
        version: '= 1.15.2'
Rakefile:
  changelog_user: puppetlabs
  changelog_max_issues: 500
spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
.gitpod.Dockerfile:
  unmanaged: false
.gitpod.yml:
  unmanaged: false
.github/workflows/nightly.yml:
  unmanaged: true
.github/workflows/pr_test.yml:
  unmanaged: true
.github/workflows/auto_release.yml:
  unmanaged: false
.github/workflows/spec.yml:
  checks: 'syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop'
  unmanaged: false
.github/workflows/release.yml:
  unmanaged: false
.travis.yml:
  delete: true
changelog_since_tag: 'v3.0.0'
Rakefile:
  extra_disabled_lint_checks:
    - relative_classname_inclusion
    - parameter_types
    - top_scope_facts
    - legacy_facts
