---
branches:
  only:
    -master
language: ruby
bundler_args: --without system_tests
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
matrix:
  fast_finish: true
  include:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.3.0"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.4.0"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.5.0"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.6.0"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.7.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.3.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.4.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.5.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.6.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.7.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.7.0"
  allowed_failures:
  - rvm: 2.1.2
    env: PUPPET_GEM_VERSION="~> 3.7.0"
notifications:
  email: false
