# frozen_string_literal: true

require 'spec_helper'
require 'puppet/resource_api'

ensure_module_defined('Puppet::Provider::Firewall')
require 'puppet/provider/firewall/firewall'

RSpec.describe Puppet::Provider::Firewall::Firewall do
  describe 'iptables-save output parsing' do
    subject(:provider) { described_class.new }

    let(:type) { Puppet::Type.type('firewall') }
    let(:context) { Puppet::ResourceApi::BaseContext.new(type.type_definition.definition) }

    describe 'get(_context)' do
      let(:iptables) do
        '
# Generated by iptables-save v1.8.4 on Thu Aug 10 10:15:14 2023
*filter
:INPUT ACCEPT [62:3308]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [39:3092]
:TEST_ONE - [0:0]
:TEST-ANOTHER - [0:0]
COMMIT
-A TEST_ONE -p tcp -m comment --comment "001 custom chain test rule"
-A INPUT -p tcp -m comment --comment "002 \"double-quotes\" test rule"
-A INPUT -p tcp -m comment --comment "007 \'single-quotes\' test rule"
-A TEST-ANOTHER -p tcp -m comment --comment "003 test -A in chain name"
-A TEST_ONE -p tcp -m comment --comment "foreign rule test"
# Completed on Thu Aug 10 10:15:14 2023
# Generated by iptables-save v1.8.4 on Thu Aug 10 10:15:14 2023
*raw
:PREROUTING ACCEPT [13222:23455532]
:OUTPUT ACCEPT [12523:852730]
COMMIT
-A OUTPUT -p tcp -m comment --comment "004 test raw table rule"
# Completed on Thu Aug 10 10:15:14 2023
        '
      end
      let(:ip6tables) do
        '
# Generated by ip6tables-save v1.8.4 on Thu Aug 10 10:21:55 2023
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [13:824]
:TEST_TWO - [0:0]
COMMIT
-A OUTPUT -p tcp -m comment --comment "005 test ipv6 rule"
# Completed on Thu Aug 10 10:21:55 2023
*raw
:PREROUTING ACCEPT [13222:23455532]
:OUTPUT ACCEPT [12523:852730]
COMMIT
-A TEST_TWO -p tcp -m comment --comment "006 test ipv6 rule in different table"
# Completed on Thu Aug 10 10:21:55 2023
        '
      end
      let(:returned_data) do
        [
          {
            chain: 'TEST_ONE',
            checksum_fill: false,
            clamp_mss_to_pmtu: false,
            clusterip_new: false,
            ensure: 'present',
            ipvs: false,
            isfirstfrag: false,
            isfragment: false,
            ishasmorefrags: false,
            islastfrag: false,
            kernel_timezone: false,
            line: '-A TEST_ONE -p tcp -m comment --comment "001 custom chain test rule"',
            log_ip_options: false,
            log_tcp_options: false,
            log_tcp_sequence: false,
            log_uid: false,
            name: '001 custom chain test rule',
            notrack: false,
            physdev_is_bridged: false,
            physdev_is_in: false,
            physdev_is_out: false,
            proto: 'tcp',
            protocol: 'IPv4',
            queue_bypass: false,
            random: false,
            random_fully: false,
            rdest: false,
            reap: false,
            rsource: false,
            rttl: false,
            socket: false,
            table: 'filter',
            time_contiguous: false
          },
          {
            chain: 'INPUT',
            checksum_fill: false,
            clamp_mss_to_pmtu: false,
            clusterip_new: false,
            ensure: 'present',
            ipvs: false,
            isfirstfrag: false,
            isfragment: false,
            ishasmorefrags: false,
            islastfrag: false,
            kernel_timezone: false,
            line: '-A INPUT -p tcp -m comment --comment "002 \"double-quotes\" test rule"',
            log_ip_options: false,
            log_tcp_options: false,
            log_tcp_sequence: false,
            log_uid: false,
            name: '002 \"double-quotes\" test rule',
            notrack: false,
            physdev_is_bridged: false,
            physdev_is_in: false,
            physdev_is_out: false,
            proto: 'tcp',
            protocol: 'IPv4',
            queue_bypass: false,
            random: false,
            random_fully: false,
            rdest: false,
            reap: false,
            rsource: false,
            rttl: false,
            socket: false,
            table: 'filter',
            time_contiguous: false
          },
          {
            chain: 'INPUT',
            checksum_fill: false,
            clamp_mss_to_pmtu: false,
            clusterip_new: false,
            ensure: 'present',
            ipvs: false,
            isfirstfrag: false,
            isfragment: false,
            ishasmorefrags: false,
            islastfrag: false,
            kernel_timezone: false,
            line: '-A INPUT -p tcp -m comment --comment "007 \'single-quotes\' test rule"',
            log_ip_options: false,
            log_tcp_options: false,
            log_tcp_sequence: false,
            log_uid: false,
            name: '007 \'single-quotes\' test rule',
            notrack: false,
            physdev_is_bridged: false,
            physdev_is_in: false,
            physdev_is_out: false,
            proto: 'tcp',
            protocol: 'IPv4',
            queue_bypass: false,
            random: false,
            random_fully: false,
            rdest: false,
            reap: false,
            rsource: false,
            rttl: false,
            socket: false,
            table: 'filter',
            time_contiguous: false
          },
          {
            chain: 'TEST-ANOTHER',
            checksum_fill: false,
            clamp_mss_to_pmtu: false,
            clusterip_new: false,
            ensure: 'present',
            ipvs: false,
            isfirstfrag: false,
            isfragment: false,
            ishasmorefrags: false,
            islastfrag: false,
            kernel_timezone: false,
            line: '-A TEST-ANOTHER -p tcp -m comment --comment "003 test -A in chain name"',
            log_ip_options: false,
            log_tcp_options: false,
            log_tcp_sequence: false,
            log_uid: false,
            name: '003 test -A in chain name',
            notrack: false,
            physdev_is_bridged: false,
            physdev_is_in: false,
            physdev_is_out: false,
            proto: 'tcp',
            protocol: 'IPv4',
            queue_bypass: false,
            random: false,
            random_fully: false,
            rdest: false,
            reap: false,
            rsource: false,
            rttl: false,
            socket: false,
            table: 'filter',
            time_contiguous: false
          },
          {
            chain: 'TEST_ONE',
            checksum_fill: false,
            clamp_mss_to_pmtu: false,
            clusterip_new: false,
            ensure: 'present',
            ipvs: false,
            isfirstfrag: false,
            isfragment: false,
            ishasmorefrags: false,
            islastfrag: false,
            kernel_timezone: false,
            line: '-A TEST_ONE -p tcp -m comment --comment "foreign rule test"',
            log_ip_options: false,
            log_tcp_options: false,
            log_tcp_sequence: false,
            log_uid: false,
            name: '9005 foreign rule test',
            notrack: false,
            physdev_is_bridged: false,
            physdev_is_in: false,
            physdev_is_out: false,
            proto: 'tcp',
            protocol: 'IPv4',
            queue_bypass: false,
            random: false,
            random_fully: false,
            rdest: false,
            reap: false,
            rsource: false,
            rttl: false,
            socket: false,
            table: 'filter',
            time_contiguous: false
          },
          {
            chain: 'OUTPUT',
            checksum_fill: false,
            clamp_mss_to_pmtu: false,
            clusterip_new: false,
            ensure: 'present',
            ipvs: false,
            isfirstfrag: false,
            isfragment: false,
            ishasmorefrags: false,
            islastfrag: false,
            kernel_timezone: false,
            line: '-A OUTPUT -p tcp -m comment --comment "004 test raw table rule"',
            log_ip_options: false,
            log_tcp_options: false,
            log_tcp_sequence: false,
            log_uid: false,
            name: '004 test raw table rule',
            notrack: false,
            physdev_is_bridged: false,
            physdev_is_in: false,
            physdev_is_out: false,
            proto: 'tcp',
            protocol: 'IPv4',
            queue_bypass: false,
            random: false,
            random_fully: false,
            rdest: false,
            reap: false,
            rsource: false,
            rttl: false,
            socket: false,
            table: 'raw',
            time_contiguous: false
          },
          {
            chain: 'OUTPUT',
            checksum_fill: false,
            clamp_mss_to_pmtu: false,
            clusterip_new: false,
            ensure: 'present',
            ipvs: false,
            isfirstfrag: false,
            isfragment: false,
            ishasmorefrags: false,
            islastfrag: false,
            kernel_timezone: false,
            line: '-A OUTPUT -p tcp -m comment --comment "005 test ipv6 rule"',
            log_ip_options: false,
            log_tcp_options: false,
            log_tcp_sequence: false,
            log_uid: false,
            name: '005 test ipv6 rule',
            notrack: false,
            physdev_is_bridged: false,
            physdev_is_in: false,
            physdev_is_out: false,
            proto: 'tcp',
            protocol: 'IPv6',
            queue_bypass: false,
            random: false,
            random_fully: false,
            rdest: false,
            reap: false,
            rsource: false,
            rttl: false,
            socket: false,
            table: 'filter',
            time_contiguous: false
          },
          {
            chain: 'TEST_TWO',
            checksum_fill: false,
            clamp_mss_to_pmtu: false,
            clusterip_new: false,
            ensure: 'present',
            ipvs: false,
            isfirstfrag: false,
            isfragment: false,
            ishasmorefrags: false,
            islastfrag: false,
            kernel_timezone: false,
            line: '-A TEST_TWO -p tcp -m comment --comment "006 test ipv6 rule in different table"',
            log_ip_options: false,
            log_tcp_options: false,
            log_tcp_sequence: false,
            log_uid: false,
            name: '006 test ipv6 rule in different table',
            notrack: false,
            physdev_is_bridged: false,
            physdev_is_in: false,
            physdev_is_out: false,
            proto: 'tcp',
            protocol: 'IPv6',
            queue_bypass: false,
            random: false,
            random_fully: false,
            rdest: false,
            reap: false,
            rsource: false,
            rttl: false,
            socket: false,
            table: 'raw',
            time_contiguous: false
          },
        ]
      end

      it 'processes the resource' do
        allow(Puppet::Util::Execution).to receive(:execute).with('iptables-save', { combine: false, failonfail: true }).and_return(iptables)
        allow(Puppet::Util::Execution).to receive(:execute).with('ip6tables-save', { combine: false, failonfail: true }).and_return(ip6tables)

        expect(provider.get(context)).to eq(returned_data)
      end

      context 'when comments contain proto-like flags' do
        let(:iptables) do
          "\n# Generated by iptables-save v1.8.4 on Thu Aug 10 10:15:14 2023\n*filter\n:INPUT ACCEPT [62:3308]\n:FORWARD ACCEPT [0:0]\n:OUTPUT ACCEPT [39:3092]\nCOMMIT\n-A INPUT -m comment --comment \"008 parser should ignore -p -p\"\n-A INPUT -m comment --comment '009 parser should ignore -p -p'\n-A INPUT -p tcp -m comment --comment \"010 parser should keep real proto despite -p -p\"\n-A INPUT -p tcp -m comment --comment '011 parser should keep real proto despite -p -p'\n# Completed on Thu Aug 10 10:15:14 2023\n          "
        end

        let(:ip6tables) do
          "\n# Generated by ip6tables-save v1.8.4 on Thu Aug 10 10:21:55 2023\n*filter\n:INPUT ACCEPT [0:0]\n:FORWARD ACCEPT [0:0]\n:OUTPUT ACCEPT [13:824]\nCOMMIT\n# Completed on Thu Aug 10 10:21:55 2023\n          "
        end

        it 'processes single-quoted and double-quoted comments without mis-parsing proto' do
          allow(Puppet::Util::Execution).to receive(:execute).with('iptables-save', { combine: false, failonfail: true }).and_return(iptables)
          allow(Puppet::Util::Execution).to receive(:execute).with('ip6tables-save', { combine: false, failonfail: true }).and_return(ip6tables)

          parsed = provider.get(context)

          expect(parsed).to include(
            a_hash_including(
              chain: 'INPUT',
              line: '-A INPUT -m comment --comment "008 parser should ignore -p -p"',
              name: '008 parser should ignore -p -p',
              protocol: 'IPv4',
              table: 'filter',
              proto: 'all'
            ),
            a_hash_including(
              chain: 'INPUT',
              line: "-A INPUT -m comment --comment '009 parser should ignore -p -p'",
              name: '009 parser should ignore -p -p',
              protocol: 'IPv4',
              table: 'filter',
              proto: 'all'
            ),
            a_hash_including(
              chain: 'INPUT',
              line: '-A INPUT -p tcp -m comment --comment "010 parser should keep real proto despite -p -p"',
              name: '010 parser should keep real proto despite -p -p',
              protocol: 'IPv4',
              table: 'filter',
              proto: 'tcp'
            ),
            a_hash_including(
              chain: 'INPUT',
              line: "-A INPUT -p tcp -m comment --comment '011 parser should keep real proto despite -p -p'",
              name: '011 parser should keep real proto despite -p -p',
              protocol: 'IPv4',
              table: 'filter',
              proto: 'tcp'
            )
          )

          expect(parsed.map { |rule| rule[:proto] }).not_to include('-p', '! -p')
        end
      end

      context 'when chain names contain option-like substrings' do
        let(:iptables) do
          "\n# Generated by iptables-save v1.8.4 on Thu Aug 10 10:15:14 2023\n*filter\n:INPUT ACCEPT [62:3308]\n:FORWARD ACCEPT [0:0]\n:OUTPUT ACCEPT [39:3092]\n:COLDFRONT-ACCESS - [0:0]\n:cali-po-_M_pLJ-KDF1NA7XPQJ-p - [0:0]\nCOMMIT\n-A cali-po-_M_pLJ-KDF1NA7XPQJ-p -p udp -m comment --comment \"012 chain name ends with -p\"\n-A COLDFRONT-ACCESS -p tcp -m comment --comment \"013 chain name contains -A\"\n# Completed on Thu Aug 10 10:15:14 2023\n          "
        end

        let(:ip6tables) do
          "\n# Generated by ip6tables-save v1.8.4 on Thu Aug 10 10:21:55 2023\n*filter\n:INPUT ACCEPT [0:0]\n:FORWARD ACCEPT [0:0]\n:OUTPUT ACCEPT [13:824]\nCOMMIT\n# Completed on Thu Aug 10 10:21:55 2023\n          "
        end

        it 'parses proto flags using token boundaries instead of substrings in the chain name' do
          allow(Puppet::Util::Execution).to receive(:execute).with('iptables-save', { combine: false, failonfail: true }).and_return(iptables)
          allow(Puppet::Util::Execution).to receive(:execute).with('ip6tables-save', { combine: false, failonfail: true }).and_return(ip6tables)

          parsed = provider.get(context)

          expect(parsed).to include(
            a_hash_including(
              chain: 'cali-po-_M_pLJ-KDF1NA7XPQJ-p',
              line: '-A cali-po-_M_pLJ-KDF1NA7XPQJ-p -p udp -m comment --comment "012 chain name ends with -p"',
              name: '012 chain name ends with -p',
              protocol: 'IPv4',
              table: 'filter',
              proto: 'udp'
            ),
            a_hash_including(
              chain: 'COLDFRONT-ACCESS',
              line: '-A COLDFRONT-ACCESS -p tcp -m comment --comment "013 chain name contains -A"',
              name: '013 chain name contains -A',
              protocol: 'IPv4',
              table: 'filter',
              proto: 'tcp'
            )
          )

          expect(parsed.map { |rule| rule[:proto] }).not_to include('-p', '! -p')
        end
      end
    end
  end
end
