name: "mend"

on:
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:

  mend:
    uses: "puppetlabs/cat-github-actions/.github/workflows/mend_ruby.yml@CAT-2117-skip-mend-for-PR-raised-from-forks"
    secrets: "inherit"
